# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://mnajarro.github.io
title: Mapping for Resilience
description: This site is intended to provide a tracing guide for volunteer mappers of the Mapping for Resilience program run out of the USAID GeoCenter.
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #


